### ISSUE TITLE
자동업데이트 미작동

### ISSUE THREAD

**Issue by norhu1130** [hslee1024/BulDakLauncher#6]
자동 업데이트가 미작동하고있는거 같습니다.
![image](https://user-images.githubusercontent.com/46096192/92110778-3135d180-ee26-11ea-8de2-24c8a32084b9.png)
이후 AutoUpdate관련 로그는 없었습니다.

**Comment by norhu1130** [comment]
근데 여기 왜 사람이없죠

**Comment by hslee1024** [comment]
자동 업데이트는 제가 Private로 레포지터리 사용중일 때 일부러 꺼두었습니다.

그리고 사실 기능 업데이트나 오류 패치 없이도 정상 작동해서 따로 업데이트를 자동으로 배포할 생각은 없었는데...

고민좀 해보겠습니다 ㅋㅋ

**Comment by norhu1130** [comment]
엌
